/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// It should not be manually edited. Re-run `vinxi dev` or `vinxi build` to regenerate.

import { createFileRoute, createRootRoute } from '@tanstack/react-router'

import { Route as rootRoute } from './routes/__root'
import { Route as IndexRoute } from './routes/index'

const IndexRouteWithPath = IndexRoute.update({ path: '/' } as any)

export const routeTree = rootRoute.addChildren([IndexRouteWithPath])
